### ISSUE TITLE
csdn密码集

### ISSUE THREAD

**Issue by Veteranback** [chen622/PasswordAnalysis#1]
能否告知一下csdn的密码集是如何获取的或者在哪可下载的吗？谢谢。

**Comment by chen622** [comment]
> 能否告知一下csdn的密码集是如何获取的或者在哪可下载的吗？谢谢。

给一个邮箱地址

**Comment by Veteranback** [comment]
807931877@qq.com
谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chen622/PasswordAnalysis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 晚上10:42
收件人:&nbsp;"chen622/PasswordAnalysis"<PasswordAnalysis@noreply.github.com&gt;;
抄送:&nbsp;"Wu"<807931877@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chen622/PasswordAnalysis] csdn密码集 (#1)





  
能否告知一下csdn的密码集是如何获取的或者在哪可下载的吗？谢谢。
  
给一个邮箱地址

**Comment by jj0908613073** [comment]
您好，我目前正在進行一項有關密碼安全性的學術研究，希望了解 CSDN 密碼資料集的研究使用情況。若您了解合法取得此資料集的方式或可供參考的研究資源，煩請告知，非常感謝！邮箱地址:61347103s@gapps.ntnu.edu.tw 謝謝

**Comment by chen622** [comment]
> 您好，我目前正在進行一項有關密碼安全性的學術研究，希望了解 CSDN 密碼資料集的研究使用情況。若您了解合法取得此資料集的方式或可供參考的研究資源，煩請告知，非常感謝！邮箱地址:[61347103s@gapps.ntnu.edu.tw](mailto:61347103s@gapps.ntnu.edu.tw) 謝謝

不好意思，数据已经被清理了。
